# Installs Node and then builds the angular application
# Taken from nodeJS azure pipeline template

trigger:
- master

resources:
  containers:
    - container: latest
      image: Ubuntu:16.04

pool:
  vmImage: 'Ubuntu 16.04'

container: latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.15'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'